package httpapi

import (
	"context"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"

	"golang.org/x/crypto/ssh"

	"github.com/google/uuid"

	"github.com/freezxp/proxui/internal/app/ports"
	"github.com/freezxp/proxui/internal/domain/shell"
	"github.com/freezxp/proxui/internal/infra/sshclient"
	"github.com/freezxp/proxui/internal/infra/sshclient/sshtest"
)

// The portal key, end to end (SSH-11..SSH-14, ADR 0006): a real SSH server, a
// real SFTP subsystem, the real HTTP router, and a key generated by the real
// generator.
//
// Two things are worth proving here and cannot be proved in a unit test. That
// installing over an open session actually lands a usable line in the
// account's authorized_keys on the far end. And that a connect asking for the
// portal key authenticates with a secret the browser never sent and never
// sees.

// memPortalKeys is the vault, in memory.
type memPortalKeys struct {
	mu       sync.Mutex
	key      shell.PortalKey
	private  string
	has      bool
	installs map[string]shell.KeyInstall
}

func newMemPortalKeys() *memPortalKeys {
	return &memPortalKeys{installs: map[string]shell.KeyInstall{}}
}

func (m *memPortalKeys) Get(context.Context) (shell.PortalKey, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if !m.has {
		return shell.PortalKey{}, ports.ErrNotFound
	}
	return m.key, nil
}

func (m *memPortalKeys) PrivateKey(context.Context) (string, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if !m.has {
		return "", ports.ErrNotFound
	}
	return m.private, nil
}

func (m *memPortalKeys) Replace(_ context.Context, key shell.PortalKey, private string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.key, m.private, m.has = key, private, true
	return nil
}

func (m *memPortalKeys) Delete(context.Context) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.has = false
	return nil
}

func (m *memPortalKeys) Installs(_ context.Context, vmID uuid.UUID) ([]shell.KeyInstall, error) {
	m.mu.Lock()
	defer m.mu.Unlock()
	out := []shell.KeyInstall{}
	for _, in := range m.installs {
		if vmID != uuid.Nil && in.VMID != vmID {
			continue
		}
		in.Stale = !m.has || in.Fingerprint != m.key.Fingerprint
		out = append(out, in)
	}
	return out, nil
}

func (m *memPortalKeys) RecordInstall(_ context.Context, in shell.KeyInstall) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	m.installs[in.VMID.String()+"/"+in.SSHUser] = in
	return nil
}

func (m *memPortalKeys) ForgetInstall(_ context.Context, vmID uuid.UUID, user string) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	delete(m.installs, vmID.String()+"/"+user)
	return nil
}

// seed puts a freshly generated pair in the store and returns its public half
// parsed the way sshd would parse it.
func (m *memPortalKeys) seed(t *testing.T) ssh.PublicKey {
	t.Helper()
	private, key, err := sshclient.GenerateKeyPair(shell.KeyComment)
	if err != nil {
		t.Fatalf("generate portal key: %v", err)
	}
	if err := m.Replace(context.Background(), key, private); err != nil {
		t.Fatalf("seed portal key: %v", err)
	}
	parsed, _, _, _, err := ssh.ParseAuthorizedKey([]byte(key.PublicKey))
	if err != nil {
		t.Fatalf("parse public key: %v", err)
	}
	return parsed
}

func TestPortalKeyInstallsIntoAuthorizedKeysOnTheGuest(t *testing.T) {
	f := newShellFixture(t, sshtest.Options{})
	f.keys.seed(t)
	session := f.open(t)
	sessionID := session["session_id"].(string)

	status, body := f.do(t, "POST", "/api/v1/ssh-sessions/"+sessionID+"/portal-key", nil)
	if status != http.StatusCreated {
		t.Fatalf("install = %d %v", status, body)
	}
	if body["ssh_user"] != "tester" {
		t.Fatalf("install recorded ssh_user %v, want tester", body["ssh_user"])
	}

	// The file on the far end is the proof. The SFTP subsystem serves the
	// server's temporary root, so the home the portal resolved is that root.
	installed := readGuestFile(t, f, ".ssh/authorized_keys")
	stored, err := f.keys.Get(context.Background())
	if err != nil {
		t.Fatalf("read seeded key: %v", err)
	}
	if !shell.HasAuthorizedKey(installed, stored.PublicKey) {
		t.Fatalf("authorized_keys on the guest does not carry the key: %q", installed)
	}
	if _, _, _, _, err := ssh.ParseAuthorizedKey([]byte(strings.TrimSpace(installed))); err != nil {
		t.Fatalf("what landed on the guest is not a line sshd can parse: %v", err)
	}
}

func TestPortalKeyConnectSendsNoSecretAndAuthenticates(t *testing.T) {
	// The server accepts exactly one key: the portal's. A password is refused,
	// so a connect that succeeds can only have used the stored key.
	private, key, err := sshclient.GenerateKeyPair(shell.KeyComment)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	authorized, _, _, _, err := ssh.ParseAuthorizedKey([]byte(key.PublicKey))
	if err != nil {
		t.Fatalf("parse: %v", err)
	}

	f := newShellFixture(t, sshtest.Options{AuthorizedKey: authorized})
	if err := f.keys.Replace(context.Background(), key, private); err != nil {
		t.Fatalf("seed: %v", err)
	}
	// No password in the body, and no private key either: a boolean is the
	// whole credential the browser sends.
	body := map[string]any{
		"username": "tester", "use_portal_key": true,
		"host": f.sshd.Host, "port": f.sshd.Port,
		"accept_host_key": f.sshd.Fingerprint,
	}
	status, session := f.do(t, "POST", "/api/v1/vms/"+f.vmID().String()+"/ssh", body)
	if status != http.StatusCreated {
		t.Fatalf("connect with the portal key = %d %v", status, session)
	}

	// And nothing in the response resembles key material.
	for k, v := range session {
		if text, ok := v.(string); ok && strings.Contains(text, "PRIVATE KEY") {
			t.Fatalf("response field %q leaked key material", k)
		}
	}

	// The audit trail names the door that was used, and no more.
	found := false
	for _, e := range f.audit.entries() {
		if e.Action == "ssh_session_opened" {
			found = true
			if e.Details["auth_method"] != "portal_key" {
				t.Fatalf("auth_method is %v, want portal_key", e.Details["auth_method"])
			}
		}
	}
	if !found {
		t.Fatal("opening a session should be audited")
	}
}

func TestPortalKeyConnectWithoutAKeyIsAClearRefusal(t *testing.T) {
	f := newShellFixture(t, sshtest.Options{})
	body := map[string]any{
		"username": "tester", "use_portal_key": true,
		"host": f.sshd.Host, "port": f.sshd.Port,
		"accept_host_key": f.sshd.Fingerprint,
	}
	status, resp := f.do(t, "POST", "/api/v1/vms/"+f.vmID().String()+"/ssh", body)
	if status != http.StatusConflict || resp["code"] != "ssh.no_portal_key" {
		t.Fatalf("want 409 ssh.no_portal_key, got %d %v", status, resp)
	}
}

func TestPortalKeyRemovalTakesTheLineBackOut(t *testing.T) {
	f := newShellFixture(t, sshtest.Options{})
	f.keys.seed(t)
	session := f.open(t)
	sessionID := session["session_id"].(string)

	// Somebody else's key is already in the file and must survive both ways.
	theirs := "ssh-rsa AAAAB3NzaC1yc2ETheirOwnKeyForTheE2E alice@laptop\n"
	writeGuestFile(t, f, ".ssh/authorized_keys", theirs)

	if status, body := f.do(t, "POST", "/api/v1/ssh-sessions/"+sessionID+"/portal-key", nil); status != http.StatusCreated {
		t.Fatalf("install = %d %v", status, body)
	}
	if status, body := f.do(t, "DELETE", "/api/v1/ssh-sessions/"+sessionID+"/portal-key", nil); status != http.StatusNoContent {
		t.Fatalf("remove = %d %v", status, body)
	}

	after := readGuestFile(t, f, ".ssh/authorized_keys")
	stored, _ := f.keys.Get(context.Background())
	if shell.HasAuthorizedKey(after, stored.PublicKey) {
		t.Fatalf("the portal key survived removal: %q", after)
	}
	if !strings.Contains(after, "TheirOwnKeyForTheE2E") {
		t.Fatalf("removal took the operator's own key with it: %q", after)
	}

	installs, _ := f.keys.Installs(context.Background(), uuid.Nil)
	if len(installs) != 0 {
		t.Fatalf("the install record should be gone, got %+v", installs)
	}
}

func TestVMKeyInstallsTellsTheConnectFormWhatToOffer(t *testing.T) {
	f := newShellFixture(t, sshtest.Options{})
	f.keys.seed(t)

	status, body := f.do(t, "GET", "/api/v1/vms/"+f.vmID().String()+"/ssh-key", nil)
	if status != http.StatusOK {
		t.Fatalf("before install = %d %v", status, body)
	}
	if data, _ := body["data"].([]any); len(data) != 0 {
		t.Fatalf("nothing is installed yet, got %v", data)
	}
	if body["key_exists"] != true {
		t.Fatalf("the portal has a key, response says %v", body["key_exists"])
	}

	session := f.open(t)
	sessionID := session["session_id"].(string)
	if status, resp := f.do(t, "POST", "/api/v1/ssh-sessions/"+sessionID+"/portal-key", nil); status != http.StatusCreated {
		t.Fatalf("install = %d %v", status, resp)
	}

	status, body = f.do(t, "GET", "/api/v1/vms/"+f.vmID().String()+"/ssh-key", nil)
	if status != http.StatusOK {
		t.Fatalf("after install = %d %v", status, body)
	}
	data, _ := body["data"].([]any)
	if len(data) != 1 {
		t.Fatalf("want one install, got %v", data)
	}
	entry, _ := data[0].(map[string]any)
	if entry["ssh_user"] != "tester" || entry["stale"] != false {
		t.Fatalf("unexpected install %v", entry)
	}
}

func TestPortalKeyEndpointNeverReturnsThePrivateHalf(t *testing.T) {
	f := newShellFixture(t, sshtest.Options{})
	f.keys.seed(t)

	status, body := f.do(t, "GET", "/api/v1/ssh-key", nil)
	if status != http.StatusOK {
		t.Fatalf("read key = %d %v", status, body)
	}
	if body["exists"] != true {
		t.Fatalf("a seeded key should exist, got %v", body)
	}
	public, _ := body["public_key"].(string)
	if !strings.HasPrefix(public, "ssh-ed25519 ") {
		t.Fatalf("public_key is %q", public)
	}
	for k, v := range body {
		if text, ok := v.(string); ok && strings.Contains(text, "PRIVATE KEY") {
			t.Fatalf("field %q leaked the private half", k)
		}
	}
}

// readGuestFile reads a path under the SSH server's SFTP root - which is what
// the portal resolved as the account's home.
func readGuestFile(t *testing.T, f *shellFixture, name string) string {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(f.sshd.Root, filepath.FromSlash(name)))
	if err != nil {
		t.Fatalf("read %s on the guest: %v", name, err)
	}
	return string(raw)
}

func writeGuestFile(t *testing.T, f *shellFixture, name, content string) {
	t.Helper()
	full := filepath.Join(f.sshd.Root, filepath.FromSlash(name))
	if err := os.MkdirAll(filepath.Dir(full), 0o700); err != nil {
		t.Fatalf("make guest dir: %v", err)
	}
	if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
		t.Fatalf("write %s on the guest: %v", name, err)
	}
}
