-- +goose Up

-- The portal's own SSH key pair (SSH-11..SSH-14, docs/adr/0006-portal-owned-ssh-key.md).
--
-- ADR 0005 refused to store guest credentials and still does: no password an
-- operator types is written here or anywhere else. What this table holds is a
-- credential the portal owns - one key pair, generated by the portal, whose
-- public half an operator installs into their own authorized_keys on guests
-- they already had a shell on.
--
-- The difference that makes it storable: revoking it is removing one line from
-- one file, it grants exactly the accounts somebody deliberately installed it
-- into, and rotating it does not require knowing any guest's password.
--
-- Envelope encryption for the private half, identical to platform_credentials:
-- sealed with a per-row data key, the data key wrapped by the master key, so
-- rotation rewraps dek_wrapped and leaves the ciphertext alone.
CREATE TABLE ssh_portal_key (
    -- One key for the portal. The constant primary key is what makes that a
    -- schema rule rather than something the application layer has to remember.
    id          boolean PRIMARY KEY DEFAULT true CHECK (id),

    algorithm   text NOT NULL,
    -- The public half, as a complete authorized_keys line. Not a secret: it is
    -- readable by any operator, because pasting it into cloud-init is one of
    -- the two supported ways to install it.
    public_key  text NOT NULL,
    fingerprint text NOT NULL,

    ciphertext  bytea NOT NULL,
    nonce       bytea NOT NULL,
    dek_wrapped bytea NOT NULL,
    dek_nonce   bytea NOT NULL,
    key_version int NOT NULL DEFAULT 1,

    created_at  timestamptz NOT NULL DEFAULT now(),
    created_by  uuid REFERENCES users(id) ON DELETE SET NULL
);

-- Where the portal believes its key is installed.
--
-- A record of what the portal did, not an authority on what the guest will
-- accept: the file on the guest is the truth, and an operator who edits it by
-- hand leaves a row here stale. It exists so the connect form can offer key
-- auth where it is likely to work, and so rotation can show an administrator
-- every line that is about to stop working.
--
-- The fingerprint is stored per row rather than joined from ssh_portal_key so
-- that a rotation leaves visibly stale rows instead of silently relabelling
-- them as installs of the new key.
CREATE TABLE ssh_key_installs (
    vm_id        uuid NOT NULL REFERENCES vms(id) ON DELETE CASCADE,
    ssh_user     text NOT NULL,
    fingerprint  text NOT NULL,
    installed_at timestamptz NOT NULL DEFAULT now(),
    installed_by uuid REFERENCES users(id) ON DELETE SET NULL,
    PRIMARY KEY (vm_id, ssh_user)
);
CREATE INDEX ix_ssh_installs_vm ON ssh_key_installs(vm_id);

-- +goose Down
DROP TABLE IF EXISTS ssh_key_installs;
DROP TABLE IF EXISTS ssh_portal_key;
